### ISSUE TITLE
Papers "Compression strategies and space-conscious representations for deep neural networks" (ICPR2020) and "Reproducing the sparse Huffman Address Map compression for deep neural networks" (RRPR2020)

### ISSUE THREAD

**Issue by dariomalchiodi** [RLPR/LabelReviews#18]
# General info
- [ ] Conference: ICPR2020 + RRPR2020
- [ ] Submission date: July 2020 (ICPR) and Nov 20th, 2020 (RRPR)
- [ ] Papers title: "Compression strategies and space-conscious representations for deep neural networks" (ICPR2020) and "Reproducing the sparse Huffman Address Map compression for deep neural networks" (RRPR2020)
- [ ] Source paper: proceedings of ICPR have not yet been published, RRPR contribution is currently under review
- [ ] GitHub repo: https://github.com/giosumarin/ICPR2020_sHAM
- [ ] Platform: Linux
- [ ] Language: English
- [ ] Results that can be reproduced: Tables II and III, Figure 3
- [ ] Reproduction main step instructions: Follow the instructions in the repository README.md .

# Reviewer feedback
 - [ ] Tested platform: 
 - [ ]  Result reproduced: 
 - [ ]  Reviewer comment:

## Details Results
- Execution without errors:
    - [ ] without changes
    - [ ] with small changes
    - [ ] with a lot of changes
- Results are obtained:
    - [ ] always
    - [ ] sometimes
    - [ ] never
- Results correspond to the paper's figures/tables:
    - [ ] exactly
    - [ ] with negligible differences
    - [ ] with differences
    - [ ] with a lot of differences

**Comment by akrah** [comment]
Hi @dariomalchiodi,
I started the review. When I run `runner.sh`, I have a lot of error messages like this one:
```bash
ImportError: No module named keras
Traceback (most recent call last):
  File "weightsharing.py", line 1, in <module>
    import keras
```
Please, could you indicate how to install all dependencies in your README.md?

**Comment by dariomalchiodi** [comment]
Thanks for the rapid feedback! Actually runner.sh should create a virtual environment and automatically install all libraries (including keras). We tested it on different machines and we didn't experience problems, so I have to figure out what is going on. My first hypothesis is that "python" might be bound to a 2.X version on the machine you are using. We have added  an alias at the beginning of runner.sh, so that "python" is explicitly bound to python 3. Could you please re-clone the repo (or pull it and delete the "venv_compr" directory created when building the virtual environment) and re-run runner.sh?

Thanking in advance,
Dario Malchiodi

**Comment by akrah** [comment]
I pulled the commits but define an alias in a shell script doesn't work: you need to add `shopt -s expand_aliases` to be able to use a defined alias. Anyway, you was right, it was the problem and I fixed it by defining an alias in the shell before to run the script.

I actually have in output the following error about th file https://github.com/giosumarin/ICPR2020_sHAM/blob/master/nets/DeepDTA/KIBA/weightsharing.py :
```bash
Using TensorFlow backend.
Traceback (most recent call last):
  File "weightsharing.py", line 143, in <module>
    TRAIN_RES = ([pre_pruning_train] + [post_pruning_train] + ws_model.acc_train)
NameError: name 'pre_pruning_train' is not defined
```
and this one about CUDA :
```bash
W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
E tensorflow/stream_executor/cuda/cuda_driver.cc:313] failed call to cuInit: UNKNOWN ERROR (303)
```
About CUDA error, probably you need to specify that there is a package/driver to install?

Actually I recommand to add the following informations for users in the `README.md` file:
- install `python3`, `python3-pip` and `python3-venv` (Debian 10.6)
- make sure that `python --version` starts by `3` or execute `alias python='pyhton3'` in the shell before to run `runner.sh`
- add informations bout CUDA?

**Comment by dariomalchiodi** [comment]
Thanks for the advice. We have a more detailed README, showing your suggested information and including a link for CUDA driver installation. We also have provided two different scripts, respectively for GPU- and CPU-based systems (in the latter only a warning about missing CUDA driver should now be issued). However, only relying on CPU is likely to require a huge amount of time.
